<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1621182027660' stop='1621182098793'>
    <name>Test Suite Device: One Plus 7Pro</name>
    <title>Test Suite Device: One Plus 7Pro</title>
    <test-cases>
        <test-case start='1621182027660' status='broken' stop='1621182098792'>
            <name>User is able to login succesfully</name>
            <title>User is able to login succesfully</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='device' value='e64ba61d-11'/>
                <parameter kind='argument' name='device' value='e64ba61d-11'/>
            </parameters>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='13818680-ce2c-4afc-a896-af3f0abce8fd-attachment.png' type='image/png' size='218609'/>
            </attachments>
            <failure>
                <message>Timed out while connecting to server</message>
                <stack-trace>Error: Timed out while connecting to server
                    at Timeout.&lt;anonymous> (/Users/chetanmalhotra/code/TestAutomation/WDIO/shareable-asset/node_modules/imap/lib/Connection.js:280:15)
                    at listOnTimeout (internal/timers.js:554:17)
                    at processTimers (internal/timers.js:497:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>